### ISSUE TITLE
Bug:Hero.java#L1755

### ISSUE THREAD

**Issue by LingASDJ** [Hoto-Mocha/Shattered-Pixel-Dungeon-Modding#278]
## Essential Infomations
- Version of the game(2.35.0) : 
- [ No ] Was your save created from previous version?
- [ No ] Did a crash occurs with the game?
- About The Bug : 
- PLANTER hero will automatically sleep when passing through HighGrass
<a href="https://github.com/Hoto-Mocha/ARranged-Pixel-Dungeon/blob/master/core/src/main/java/com/shatteredpixel/shatteredpixeldungeon/actors/hero/Hero.java#L1755" target="_blank"><h3>BUG Key Point! Please Fixed!</h3></a>

## Optional Infomations
You can test it yourself.  
It is recommended that you test it before releasing the version.

**Comment by Hoto-Mocha** [comment]
Its fixed in v2.36.0, thanks a lot for picking the point.
P.S. my job is not developer(and I have poor coding skills compare with REAL developers), and I don't spend many time for tesing my game. I fix bugs what reported from user, so I recommend you not to look forward some of 'developer-ish' things from me.
I already knew that its important to check their works for developer and customer, but I don't want to swim in a pool of normally functioning codes and find problems that I don't even know where. So I shifted debugging things to user, and I have left the report page open to hear user's voice.

**Comment by LingASDJ** [comment]
You're welcome. This is what I should do.

**Comment by Hoto-Mocha** [comment]
Fixed in v2.36.0.
