### ISSUE TITLE
The huntress's bow needs to be re-identified after evolve to a poison bow

### ISSUE THREAD

**Issue by sjsxmd** [Hoto-Mocha/Shattered-Pixel-Dungeon-Modding#298]
## Essential Infomations(Use English Please)
- Version of the game(Ex.2.41.0) : 2.43.0
- [yes ] Was your save created from previous version?
- [ no] Did a crash occurs with the game?
- About The Bug : 
- Bug Occurrence Conditions :
1.The huntress's bow needs to be re-identified after evolve to a poison bow
2.The huntress's bow after evolution, there will be bows that have appeared before

## Optional Infomations
- Screenshot :

**Comment by Hoto-Mocha** [comment]
![image](https://user-images.githubusercontent.com/76470428/214092426-e7d171a1-1502-499d-8d8e-667c91f02085.png)
As a result of the test, there were no problems. I have fixed this issue in the previous version(v2.35.0), and since most of the problems with the previous save cannot be solved in the current version, I recommend that you create and play a new save after the update.
