### ISSUE TITLE
Guns AP-HP bullets question/suggestion 

### ISSUE THREAD

**Issue by Omicronrg9** [Hoto-Mocha/Shattered-Pixel-Dungeon-Modding#58]
Hi.

I am sure you're still working on the first release of your mod and that you have things pretty much clear regarding what you want to do but let me ask:

Is it intended that if I have a +3 gun and I improve it via alchemy with arcane resin + AP/HP bullet its upgrades dissappear?   I do not really see the need for that "punishment", as players often would naturally invest some Scrolls of upgrade in their preferred gun and try to make it better using everything available to them, including the alchemy enhancement.

Kind regards and my best wishes for your project,

Omicrón.

**Comment by Hoto-Mocha** [comment]
Thanks for playing despite of the game not supports English.

Reloading HP/AP ammunition is a kind of "boost" for +0 guns.
When making some weapons with alchemy, the upgrade level that fixed +0 was not intended when it was first made, but I thought that this could soon help narrow the performance gap between +0 and upgraded weapons.

Nevertheless, if you still want to make alchemy weapon, you have to be borne this, because alchemy weapons are more powerful than other normal weapons.

**Comment by Omicronrg9** [comment]
Understood, one more question though.

Suppose that I improve a +0 gun with that special ammo. Would upgrading it break that improvement?

Thanks for the early response!

**Comment by Hoto-Mocha** [comment]
No, once you make alchemy weapon, upgrading it would not affect nothing to the performance.

**Comment by Omicronrg9** [comment]
Okay! Thank you. Guess it's time to close this issue.
